#!/usr/bin/env python3
"""Regenerate REF and P32 golden vectors from live code. Does not touch LEGACY archive."""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from hqh539 import T3, STEPS, iterate_n_steps, hqh_539_512, hqh_539_256  # noqa: E402
from profiles import hqh_539_512_p32, hqh_539_256_p32  # noqa: E402


def main() -> int:
    ref = {
        "profile": "REF",
        "profile_name": "canonical_reference_min_bytes_finalize",
        "provenance": "regenerated by scripts/regenerate_goldens.py from hqh539.py",
        "t3": {str(n): T3(n) for n in (0, 4, 5, 7, 9)},
        "iterate_n_steps_539": {
            str(n): iterate_n_steps(n, STEPS) for n in (10**18, 10**19, 10**20)
        },
        "hqh_539_512": {
            "empty": hqh_539_512(b"", b""),
            "canonical": hqh_539_512("The universe counts in threes.", b""),
            "large_int": hqh_539_512(str(10**18), b""),
            "salted": hqh_539_512("The universe counts in threes.", b"hqh539-2026"),
        },
        "hqh_539_256_prefix": hqh_539_256("The universe counts in threes."),
    }
    p32 = {
        "profile": "P32",
        "profile_name": "product_deploy_fixed_32byte_finalize",
        "provenance": "regenerated by scripts/regenerate_goldens.py from profiles.py",
        "hqh_539_512": {
            "empty": hqh_539_512_p32(b"", b""),
            "canonical": hqh_539_512_p32("The universe counts in threes.", b""),
            "large_int": hqh_539_512_p32(str(10**18), b""),
            "salted": hqh_539_512_p32("The universe counts in threes.", b"hqh539-2026"),
        },
        "hqh_539_256_prefix": hqh_539_256_p32("The universe counts in threes."),
    }
    (ROOT / "golden_vectors.json").write_text(json.dumps(ref, indent=2) + "\n", encoding="utf-8")
    (ROOT / "golden_vectors_p32.json").write_text(json.dumps(p32, indent=2) + "\n", encoding="utf-8")
    print("OK: REF + P32 goldens regenerated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
